### ISSUE TITLE
cursor is black

### ISSUE THREAD

**Issue by gustavnikolaj** [JonathanMH/nothrill-dark-syntax#1]
Using atom with "One Dark" UI theme and nothrill-dark-syntax I get a black cursor on a grey background. It's very hard to see:

![screenshot from 2016-03-15 00-03-43](https://cloud.githubusercontent.com/assets/1371503/13762779/8b398246-ea41-11e5-87ef-ff7dffc28243.png)

Is that intended, or is it a result of a poor combination of syntax and UI theme? I tried "Atom Dark" and that didn't help much.

**Comment by gustavnikolaj** [comment]
It's a bit hard to see, but just right of the last d there's a thin black cursor.

**Comment by JonathanMH** [comment]
Working on it, will update tonight gmt+1

**Comment by JonathanMH** [comment]
fixed by https://github.com/JonathanMH/nothrill-dark-syntax/commit/9949bfa8e7910d8b73f305a41ba276a3f1953596

**Comment by gustavnikolaj** [comment]
Confirmed fixed :+1:
