### ISSUE TITLE
regexes highlighted in bright blue

### ISSUE THREAD

**Issue by gustavnikolaj** [JonathanMH/nothrill-dark-syntax#2]
If you enable javascript mode and enter the following:

``` js
var regex = /foo/;
```

`foo` will be highlighted in a bright blue color.

As far as I understood, the only highlight should be the comments in a slightly different tone of grey. :-)

**Comment by JonathanMH** [comment]
Thanks for the report, will fix!

**Comment by JonathanMH** [comment]
fixed by https://github.com/JonathanMH/nothrill-dark-syntax/commit/9949bfa8e7910d8b73f305a41ba276a3f1953596

**Comment by gustavnikolaj** [comment]
Confirmed fixed :+1:

**Comment by gustavnikolaj** [comment]
Sorry for the issue highjacking here... This bug also occurs in the [light fork](https://github.com/fasterthanlime/nothrill-light-syntax) by @fasterthanlime.

Because it's a fork, I cannot post an issue there, so I'm hoping to catch the authors attention here :-)

**Comment by JonathanMH** [comment]
oh, I did not know it worked like that! yes, maybe they should live as separate repos instead

no problem

**Comment by gustavnikolaj** [comment]
There's no way to "unfork" a fork in the UI - other than:
1. pulling down the code to your local machine
2. deleting the repo on github
3. creating it again (as a normal new repo)
4. pushing the code up.

I've heard that GitHub support can be helpful and remove the fork-status from a repo too, but it's not too problematic to do it yourself - especially when you don't have any issues that can get lost :-)

**Comment by fasterthanlime** [comment]
@gustavnikolaj @JonathanMH I just recreated the repo as a non-fork, as per your request, & fixed the issue in my fork. Thanks for reporting!

**Comment by fasterthanlime** [comment]
(note that I won't be able to publish the fixed version until https://github.com/atom/apm/issues/524 is resolved)

**Comment by fasterthanlime** [comment]
apm problems were fixed by GitHub staff, I've been able to push v0.7.1 which fixes these issues

**Comment by JonathanMH** [comment]
We're so great at this whole version thing ^^ **not** :D
